version: '3'

services:
  dev:
    build: .
    image: richcat_guess_lexer_dev
    container_name: richcat_guess_lexer_dev
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: "./"
        target: "/home/"
    tty: true
